language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install zope.interface
  - pip install zope.lifecycleevent
  - pip install zope.component
  - pip install zope.deprecation
  - pip install ZODB3==3.11.0
  - pip install https://github.com/conestack/odict/archive/master.zip
  - pip install https://github.com/conestack/plumber/archive/master.zip
  - pip install https://github.com/conestack/node/archive/master.zip
  - pip install .

script: python -m node.ext.zodb.tests
